# Generated by Django 2.0.3 on 2018-03-22 16:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNo', models.IntegerField(validators=[django.core.validators.MinValueValidator(7000000000), django.core.validators.MaxValueValidator(7999999999)])),
                ('isManager', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start', models.DateTimeField()),
                ('End', models.DateTimeField()),
                ('ShiftNotes', models.TextField(blank=True)),
                ('Employees', models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Schedule.Employees')),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='Availability',
            field=models.ManyToManyField(blank=True, to='Schedule.Shifts'),
        ),
        migrations.AddField(
            model_name='employees',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
