# Generated by Django 2.0.3 on 2018-03-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0003_shifts_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Availability',
            field=models.ManyToManyField(blank=True, default=None, to='Schedule.Shifts'),
        ),
    ]
