# Generated by Django 2.1.7 on 2019-02-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0004_auto_20180328_2148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalSettings',
        ),
    ]
